name: release
on:
  push:
    tags:
      - '*'

env:
  binary-name: mybooklibrary
  version: 1.6.3
  arch: linux-x64
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install 22
          node -v
          nvm current
          npm -v
          npm install -D vite
          cd mybooklibrary/frontend-ui && npm install && npm install vue-router@4 && npm install notie && make dist
          cd ../backend-api && make build_linux
          cd ../..
          mkdir ${{ env.binary-name }}-${{ env.arch }}-${{ env.version }}
          mv mybooklibrary/frontend-ui/dist ${{ env.binary-name }}-${{ env.arch }}-${{ env.version }}/
          mv mybooklibrary/backend-api/mybooklibrary-api ${{ env.binary-name }}-${{ env.arch }}-${{ env.version }}/
          #ls -al ${{ env.binary-name }}-${{ env.arch }}-${{ env.version }}        
          tar -czf ${{ env.binary-name }}-${{ env.arch }}-${{ env.version }}.tar.gz ${{ env.binary-name }}-${{ env.arch }}-${{ env.version }}/
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.DEVOPS_TOKEN }}
          tag_name: ${{ env.version }}
          name: release ${{ env.version }}
          files: ${{ env.binary-name }}-${{ env.arch }}-${{ env.version }}.tar.gz